# Generated by Django 5.2 on 2026-07-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usertype', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
