# Generated by Django 5.2 on 2026-08-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
